```{r load_genes, eval=EXPERIMENT >= 1 & EXPERIMENT <= 4}
# load data ####
genes <- read.table(file = paste0(WD_DIR, FILE),
                    sep = "\t",
                    header = TRUE,
                    check.names = FALSE) # avoid R to modify colnames
# save all genes for GSEA analyses
genes_gsea <- genes
```

```{r format_1, eval=EXPERIMENT==1, include=EXPERIMENT==1}
# 1: output table from RSeqFlow (AllGenes_allContrast)
# give format to the data ####
# nos quedamos con las columnas Coef y Results de la variable genes.
keep <- 1 # gene ID column
keep <- append(keep, grep("^Results", colnames(genes)))
keep <- append(keep, grep("^Coef", colnames(genes)))
genes <- genes[, keep]

# definimos las comparaciones
allContrasts <- colnames(genes)
allContrasts <- allContrasts[-1] # remove gene ID column
allContrasts <- gsub("Results.", "", allContrasts)
allContrasts <- gsub("Coef.", "", allContrasts)
allContrasts <- unique(allContrasts)

# creamos una lista vacía
genes_list <- list()

# r va a ser Results, que empieza en 2
r <- 2
# j va a ser Coef, que empieza en r + length(allContrasts)
j <- r+length(allContrasts)

# rellenamos la lista con los genes
for (i in r:(length(allContrasts)+1))
{
  # guardamos en una variable las columnas Results y Coef de i y j
  tmp <- genes[, c(1, i, j)] # keep column 1 for gene ID
  # eliminamos los 0 de Results
  tmp <- tmp[tmp[2]!=0, ]
  
  # los separamos en
  # genes up
  tmp_up <- tmp[tmp[2] == 1, ]
  # eliminamos segunda columna
  tmp_up[2] <- NULL
  # y genes down
  tmp_down <- tmp[tmp[2] == -1, ]
  # eliminamos segunda columna
  tmp_down[2] <- NULL
  
  # guardamos los genes separados en la lista
  name <- paste0(allContrasts[i-1], "_up")
  genes_list[[name]] <- tmp_up
  name <- paste0(allContrasts[i-1], "_down")
  genes_list[[name]] <- tmp_down
  
  # sumamos un 1 a j
  j <- j+1
}

# eliminamos variables innecesarias
rm(genes, tmp, tmp_down, tmp_up)
```

```{r format_2, eval=EXPERIMENT==2, include=EXPERIMENT==2}
# format the data ####
allContrasts <- unique(genes[[2]])
genes_list <- list()
for (i in 1:length(allContrasts))
{
  tmp <- grep(paste0("^", allContrasts[i], "$"), genes[[2]])
  tmp <- genes[tmp,1]
  genes_list[[allContrasts[i]]] <- tmp
}
rm(genes, tmp)
```

```{r format_3, eval=EXPERIMENT==3, include=EXPERIMENT==3}
# format the data ####
allContrasts <- paste0(FIRST_COND, ".", SECOND_COND)
genes_list <- list()

# check if GSEA analyses will be performed
if (exists("DEG_OE")) {
  DO_GSEA_3 <- TRUE
  # extract DEGs for the over-enrichment analyses
  tmp <- read.table(file = DEG_OE,
                    sep = "\t",
                    header = FALSE,
                    check.names = FALSE) # avoid R to modify colnames
  tmp <- genes[genes[[1]] %in% tmp[[1]], ]
} else {
  DO_GSEA_3 <- FALSE
  tmp <- genes
}
tmp_up <- tmp[tmp[COLFC] > 0, ]
tmp_down <- tmp[tmp[COLFC] < 0, ]
genes_list[[paste0(allContrasts, "_up")]] <- tmp_up[, 1]
genes_list[[paste0(allContrasts, "_down")]] <- tmp_down[, 1]

rm(genes, tmp_up, tmp_down)
```

```{r format_4, eval=EXPERIMENT==4, include=EXPERIMENT==4}
# format the data ####
genes_list <- list()
genes_list[["gene_list"]] <- genes
rm(genes)
```

```{r format_5, eval=EXPERIMENT==5, include=EXPERIMENT==5}
file_names <- ls(pattern = "FILE_\\d+")
FILE <- unlist(mget(file_names, envir = .GlobalEnv))
counts <- list()
for (i in 1:length(FILE)) {
  counts[[FILE_NAME[i]]] <- read.table(file = paste0(WD_DIR,
                                                     FILE[i]),
                                       sep = "\t",
                                       header = TRUE,
                                       check.names = FALSE)
}
# keep columns of interest
genes_list <- list()
for (i in 1:length(counts)) {
  tmp <- counts[[i]][, c(ID_COL, FC_COL), drop = FALSE]
  colnames(tmp) <- c("GeneID", "log2(foldchange)")
  # # split up and down
  tmp_up <- tmp[tmp[[2]] > 0, ]
  tmp_down <- tmp[tmp[[2]] < 0, ]
  name <- names(counts[i])
  genes_list[[paste0(name, ">control")]] <- tmp_up
  genes_list[[paste0(name, "<control")]] <- tmp_down
}
```


```{r load_ort, eval=!is.na(ORTHOLOGY_FILE) , include=!is.na(ORTHOLOGY_FILE)}
ort <- read.table(file = ORTHOLOGY_FILE,
                  sep = "\t",
                  header = TRUE)
# keep only study and reference reference columns (in that order)
ort <- ort[, c(STUDY_COLUMN, REFERENCE_COLUMN)]
```

