Analyse the **`r ONT` hierarchy** of Gene Ontology.

```{r}
# create sublist for over-enrichment analysis
LIST_LEVEL <- paste0(ONT, "-OE")
enrichment_list[[LIST_LEVEL]] <- list()
to_save[[LIST_LEVEL]] <- list()
number_genes_enrichment[[LIST_LEVEL]] <- list()
# fill the sublist with over-enrichment results
for (i in 1:length(genes_list_arab))
{
  if (ncol(genes_list_arab[[1]])==1) {
    col <- 1
  } else {
    col <- 2
  }
  temp <- enrichGO(gene = genes_list_arab[[i]][[col]],
                   OrgDb = organism,
                   keyType = KEYTYPE,
                   ont = ONT,
                   pvalueCutoff = P_CUTOFF,
                   qvalueCutoff = Q_CUTOFF,
                   pAdjustMethod = P_ADJUST_METHOD,
                   minGSSize = MIN_GSSIZE,
                   maxGSSize = MAX_GSSIZE,
                   readable = FALSE,
                   pool = FALSE)
  
  temp@result$CountBg <- temp@result$Count / as.numeric(gsub("/.*", "",temp@result$BgRatio))
  # save before filter
  if (nrow(temp)) {
    name <- names(genes_list_arab)[i]
    to_save[[LIST_LEVEL]][[name]] <- temp
  }
  
  # remove GO terms redundancy
  if (DO_REMOVE_REDUNDANCY) {
    temp <- simplify(temp, cutoff = 0.7, by = "p.adjust", select_fun = min)
  }
  # filter at specific level
  if (GO_LEVEL) {
    temp <- gofilter(temp, level = GO_LEVEL)
  }
  
  # # check if there was enrichment
  # empty <- length(temp$ID) == 0
  # # if it's empty we don't save it in the list
  if (nrow(temp))
  {
    # save values in the list
    name <- names(genes_list_arab)[i]
    enrichment_list[[LIST_LEVEL]][[name]] <- temp
    # save number of genes analysed in a vector
    number_genes_enrichment[[LIST_LEVEL]][[name]] <- length(genes_list_arab[[i]][[col]])
  } else {
    message(paste0("0 enrichment terms found for ", names(genes_list_arab)[i]))
  }
}

rm(temp)
```

Remove empty list elements, if any.

```{r}
#remove empty list(s) before plot
length_loop <- length(enrichment_list)
for (i in 1:length_loop) {
  if (length(enrichment_list[[i]]) == 0) {
    enrichment_list[[i]] <- NULL
    length_loop <- length_loop - 1
    }
}
```

```{r}
# check if the process is empty so things won't be plotted
PROCESS <- !is.null(enrichment_list[[LIST_LEVEL]])
if (!PROCESS) {
  message(LIST_LEVEL, " has no enriched terms, so it will be skipped")
}
```

```{r, eval=(EVAL_TF && PROCESS), child='11_TF.Rmd'}
```

```{r, eval=PROCESS, child='12_Plots.Rmd'}
```

```{r, eval=MODEL_REFERENCE==FALSE && PROCESS, include=MODEL_REFERENCE==FALSE && PROCESS}
# Convert IDs Arabidopsis to original organism and save (if the orthology was performed)
# create dataframe to save data
enriched_genes <- list()
for (i in 1:length(enrichment_list[[LIST_LEVEL]])) {
  tmp <- enrichment_list[[LIST_LEVEL]][[i]]@result
  # filter results to keep only significant
  # because in @result all the genes are saved
  tmp <- tmp[tmp$p.adjust <= P_CUTOFF, ]
  tmp <- tmp[tmp$qvalue <= Q_CUTOFF,]
  tmp <- tmp[, c(2, 8)]
  name <- names(enrichment_list[[LIST_LEVEL]])[i]
  final <- data.frame()
  for (j in 1:nrow(tmp)) {
    tmp2 <- tmp[j, 2]
    tmp2 <- as.data.frame(t(read.table(text = tmp2, sep = "/")))
    tmp2$process <- tmp[j,1]
    colnames(tmp2)[1] <- ORG_ENRICH
    final <- rbind(final, tmp2)
  }
  # merge with genes_list_arab to get the orthology
  tmpy <- genes_list_arab[[name]]
  tmpy <- tmpy[, c(1, 2)]
  tmp3 <- merge(x = final, y = tmpy,
                by.x = 1, by.y = 2,
                all = FALSE)
  tmp3 <- tmp3[order(tmp3$process, decreasing = FALSE), ]
  # save in the list
  enriched_genes[[name]] <- tmp3
}
save_enriched_genes <- as.data.frame(do.call(rbind, enriched_genes))
save_enriched_genes$condition <- rownames(save_enriched_genes)
save_enriched_genes$condition <- gsub("\\.[0-9].*", "", save_enriched_genes$condition)
# reorder dataframe
save_enriched_genes <- save_enriched_genes[, c(4, 1, 3, 2)]
write.table(save_enriched_genes,
            file = paste0(SUB_DIR,
                          LIST_LEVEL,
                          "_genes_",
                          tolower(gsub("ID_", "", ORG_ENRICH)),
                          "_",
                          tolower(gsub("ID_", "", ORG_ORIG)),
                          ".tsv"),
            quote = FALSE,
            sep = "\t",
            row.names = FALSE)

# remove useless variables
rm(tmp, name, final, tmp2, tmpy, tmp3, enriched_genes, save_enriched_genes)
```


